import {Problem,hash,now,clean,cents,one,order,view,transaction,enqueue} from './core.mjs';
const settled=['paid','refunded','partially_refunded','review_required'];
export function check(r,s){if(!['card','paypal'].includes(r.payment)||r.status==='cancelled')throw new Problem('invalid_payment_state',409);if(!s.paypalEnabled)throw new Problem('payment_unavailable',503);if(r.paypal_env!==s.paypalEnv||r.paypal_account!==hash(s.clientId))throw new Problem('payment_environment_changed',409);}
export function provider(s,fetcher=fetch){return async(path,body,requestId)=>{const base=s.paypalEnv==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com';try{const auth=await fetcher(base+'/v1/oauth2/token',{method:'POST',headers:{Authorization:'Basic '+Buffer.from(s.clientId+':'+s.secret).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials',signal:AbortSignal.timeout(12000)});if(!auth.ok)throw Error();const token=(await auth.json()).access_token;if(!token)throw Error();const response=await fetcher(base+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(requestId?{'PayPal-Request-Id':requestId}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(18000)});if(!response.ok)throw Error();return await response.json()}catch{throw new Problem('payment_service_error',502)}};}
export function verify(result,r){const units=result.purchase_units;if(result.id!==r.paypal_id||result.intent!=='CAPTURE'||!Array.isArray(units)||units.length!==1)throw new Problem('payment_order_mismatch',409);const u=units[0];if(u.custom_id!==r.id||u.reference_id!==r.id)throw new Problem('payment_order_mismatch',409);if(u.amount?.currency_code!=='USD'||cents(u.amount?.value)!==cents(r.usd))throw new Problem('payment_amount_mismatch',409);return u;}
export async function payCreate(pool,id,token,s,pp=provider(s)){
 const r=await transaction(pool,async c=>{const r=await order(c,id,token,true);check(r,s);if(settled.includes(r.payment_status))throw new Problem('already_processed',409);if(r.paypal_id)return r;if(r.paypal_started&&now()-r.paypal_started>18000)throw new Problem('payment_review_required',409);await c.query("UPDATE orders SET paypal_started=COALESCE(paypal_started,$1),payment_phase='started' WHERE id=$2",[now(),id]);return r;});if(r.paypal_id)return {orderId:r.paypal_id};
 const result=await pp('/v2/checkout/orders',{intent:'CAPTURE',purchase_units:[{reference_id:id,custom_id:id,amount:{currency_code:'USD',value:r.usd}}]},'create-'+id);const ppId=clean(result.id,1,100,'payment_service_error');if(!/^[A-Za-z0-9-]+$/.test(ppId))throw new Problem('payment_service_error',502);
 return transaction(pool,async c=>{const current=await order(c,id,token,true);if(current.paypal_id&&current.paypal_id!==ppId)throw new Problem('payment_order_mismatch',409);await c.query('UPDATE orders SET paypal_id=$1 WHERE id=$2',[ppId,id]);return {orderId:ppId};});
}
export async function reconcile(pool,id,s,expected,pp=provider(s)){
 const r=await order(pool,id);check(r,s);if(!r.paypal_id||(expected!==undefined&&expected!==r.paypal_id))throw new Problem('payment_order_mismatch',409);if(settled.includes(r.payment_status))return view(r);
 let result=await pp('/v2/checkout/orders/'+r.paypal_id);verify(result,r);
 if(result.status==='APPROVED'){try{await pp('/v2/checkout/orders/'+r.paypal_id+'/capture',{},'capture-'+id)}catch{/* Capture may have succeeded despite a timeout. */}result=await pp('/v2/checkout/orders/'+r.paypal_id)}
 const unit=verify(result,r),caps=unit.payments?.captures||[],completed=caps.filter(x=>x.status==='COMPLETED');
 if(result.status==='COMPLETED'&&completed.length===1){const cap=completed[0];if(caps.length!==1||!cap.id||cap.amount?.currency_code!=='USD'||cents(cap.amount?.value)!==cents(r.usd))throw new Problem('payment_amount_mismatch',409);await transaction(pool,async c=>{const current=await order(c,id,undefined,true);if(settled.includes(current.payment_status))return;const payer=result.payer||result.payment_source?.paypal||{};const paid=await one(c,"UPDATE orders SET payment_status='paid',payment_phase='completed',capture_id=$1,payer_id=$2,payer_email=$3 WHERE id=$4 RETURNING *",[cap.id,payer.payer_id||payer.account_id||null,payer.email_address||null,id]);await enqueue(c,paid,s,'DRIVEBOX payment — '+id);});}
 else if(caps.some(x=>['DECLINED','DENIED','FAILED'].includes(x.status)))await pool.query("UPDATE orders SET payment_status='failed',payment_phase='failed' WHERE id=$1 AND payment_status IN ('pending','unpaid','failed','cancelled')",[id]);
 return view(await order(pool,id));
}
export async function cancel(pool,id,token,s){return transaction(pool,async c=>{const r=await order(c,id,token,true);check(r,s);if(!settled.includes(r.payment_status))await c.query("UPDATE orders SET payment_status='cancelled',payment_phase='cancelled' WHERE id=$1",[id]);return view(await order(c,id));});}
export async function changeMethod(pool,id,token,method,s){return transaction(pool,async c=>{const r=await order(c,id,token,true);if(r.paypal_id||r.paypal_started||r.status!=='new'||settled.includes(r.payment_status))throw new Problem('payment_review_required',409);const online=['card','paypal'].includes(method);if(!online&&method!=='cash_on_delivery'||online&&!s.paypalEnabled||method==='cash_on_delivery'&&!s.cod)throw new Problem('payment_unavailable',503);await c.query("UPDATE orders SET payment=$1,payment_status=$2,usd=$3,paypal_env=$4,paypal_account=$5,payment_phase='method_changed' WHERE id=$6",[method,online?'pending':'cash_on_delivery',online?(Math.round(r.body.totalCents/s.rate)/100).toFixed(2):null,online?s.paypalEnv:null,online?hash(s.clientId):null,id]);return view(await order(c,id));});}
export async function webhook(pool,p,headers,s,pp=provider(s)){
 if(!s.webhook)throw new Problem('payment_unavailable',503);const verifyBody={webhook_id:s.webhook,webhook_event:p};for(const k of ['auth_algo','cert_url','transmission_id','transmission_sig','transmission_time'])verifyBody[k]=headers.get('paypal-'+k.replaceAll('_','-'))||'';
 if((await pp('/v1/notifications/verify-webhook-signature',verifyBody)).verification_status!=='SUCCESS')throw new Problem('invalid_signature',403);const event=clean(p.id,1,200),kind=p.event_type,resource=p.resource||{};if(await one(pool,'SELECT id FROM events WHERE id=$1',[event]))return {ok:true};const ppId=kind==='CHECKOUT.ORDER.APPROVED'?resource.id:resource.supplementary_data?.related_ids?.order_id;const row=ppId?await one(pool,'SELECT * FROM orders WHERE paypal_id=$1',[ppId]):null;
 if(['CHECKOUT.ORDER.APPROVED','PAYMENT.CAPTURE.COMPLETED'].includes(kind)&&row)await reconcile(pool,row.id,s,ppId,pp);
 await transaction(pool,async c=>{
 await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',['event:'+event]);if(await one(c,'SELECT id FROM events WHERE id=$1',[event]))return;
 if(['PAYMENT.CAPTURE.DENIED','PAYMENT.CAPTURE.PENDING'].includes(kind)&&row){const r=await order(c,row.id,undefined,true);check(r,s);if(resource.amount?.currency_code!=='USD'||cents(resource.amount?.value)!==cents(r.usd))throw new Problem('payment_amount_mismatch',409);const state=kind.endsWith('DENIED')?'failed':'pending';if(!settled.includes(r.payment_status))await c.query('UPDATE orders SET payment_status=$1,payment_phase=$1 WHERE id=$2',[state,r.id]);}
 if(['PAYMENT.CAPTURE.REFUNDED','PAYMENT.CAPTURE.REVERSED'].includes(kind)){
 let capture=resource.supplementary_data?.related_ids?.capture_id;for(const link of resource.links||[]){const m=/\/v2\/payments\/captures\/([A-Za-z0-9]+)(?:$|[?])/.exec(link.href||'');if(m)capture=m[1];}if(kind.endsWith('REVERSED'))capture=resource.id;const r=await one(c,'SELECT * FROM orders WHERE capture_id=$1 FOR UPDATE',[capture||null]);if(!r)throw new Problem('payment_order_mismatch',409);check(r,s);let state='review_required';if(kind.endsWith('REFUNDED')){const amount=cents(resource.amount?.value);if(resource.amount?.currency_code!=='USD'||amount<=0)throw new Problem('payment_amount_mismatch',409);const refundId=clean(resource.id,1,100);await c.query('INSERT INTO refunds(id,order_id,cents) VALUES($1,$2,$3) ON CONFLICT(id) DO NOTHING',[refundId,r.id,amount]);const refund=await one(c,'SELECT * FROM refunds WHERE id=$1',[refundId]);if(refund.order_id!==r.id||refund.cents!==amount)throw new Problem('payment_order_mismatch',409);const sum=Number((await one(c,'SELECT SUM(cents) AS total FROM refunds WHERE order_id=$1',[r.id])).total);if(sum>cents(r.usd))throw new Problem('payment_amount_mismatch',409);state=sum===cents(r.usd)?'refunded':'partially_refunded';}await c.query('UPDATE orders SET payment_status=$1,payment_phase=$1 WHERE id=$2',[state,r.id]);}
 await c.query('INSERT INTO events(id,created) VALUES($1,$2) ON CONFLICT DO NOTHING',[event,now()]);});return {ok:true};
}
