let orders=[];const $=s=>document.querySelector(s),labels={new:'Новый',confirmed:'Подтверждён',shipped:'Отправлен',delivered:'Доставлен',cancelled:'Отменён',unpaid:'Не оплачен',paid:'Оплачен',review_required:'Проверка платежа',cash_on_delivery:'При получении',card:'Банковская карта',pending:'Ожидает оплаты',failed:'Ошибка оплаты',refunded:'Возврат',partially_refunded:'Частичный возврат',cod:'При получении',paypal:'PayPal',test:'Тест'};
async function request(path,data){const r=await fetch('/api/admin/'+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const j=await r.json();if(!r.ok)throw Error(j.error);return j}
function message(e){$('#message').textContent=({unauthorized:'Неверный пароль или сеанс завершён.',rate_limit:'Слишком много попыток входа. Повторите через 15 минут.',payment_required:'Сначала дождитесь оплаты.',paypal_review_required:'Отмена PayPal требует проверки/возврата в платёжном кабинете.',invalid_status:'Недопустимый переход статуса.'})[e.message]||'Не удалось выполнить действие. Повторите попытку.'}
async function load(){try{orders=await request('orders');const r=await request('readiness');$('#login').hidden=true;$('#dashboard').hidden=false;$('#readiness').textContent=(r.testMode?'ТЕСТОВЫЙ РЕЖИМ. ':'')+'Неотправленных уведомлений: '+r.unsentEmails+'. '+(r.issues.length?'Для запуска: '+r.issues.join(', '):'Настройки запуска заполнены.');render()}catch(e){message(e);if(e.message==='unauthorized'){$('#login').hidden=false;$('#dashboard').hidden=true}}}
function render(){const root=$('#orders');root.replaceChildren();for(const o of orders.filter(o=>!$('#filter').value||o.status===$('#filter').value)){const card=document.createElement('article');card.className='admin-order';function add(tag,text){const n=document.createElement(tag);n.textContent=text;card.append(n);return n}add('h2',o.id+' · '+(labels[o.status]||o.status));add('p',new Date(o.createdAt*1000).toLocaleString('ru-RU',{timeZone:'Asia/Tbilisi'})+' · '+(o.testMode?'ТЕСТ':'Заказ'));add('p',o.name+' · '+o.phone+(o.email?' · '+o.email:''));add('p',o.city+', '+o.address+' · '+(o.deliveryMethod==='same'?'Сегодня':'Следующий день / региональная доставка'));for(const item of o.items)add('p',item.name.ru+' × '+item.qty+' = '+(item.unitCents*item.qty/100).toFixed(2)+' ₾');add('p','Итого '+(o.totalCents/100).toFixed(2)+' ₾ · '+labels[o.paymentMethod]+' · '+labels[o.paymentStatus]);if(o.notes)add('p','Комментарий: '+o.notes);if(o.paymentMethod==='cash_on_delivery'&&o.status==='delivered'&&o.paymentStatus==='cash_on_delivery'){const collect=add('button','Подтвердить получение денег');collect.className='btn primary';collect.onclick=async()=>{try{await request('collect',{id:o.id});await load()}catch(e){message(e)}}}const select=add('select','');select.setAttribute('aria-label','Статус '+o.id);for(const status of [o.status,...({new:['confirmed','cancelled'],confirmed:['shipped','cancelled'],shipped:['delivered'],delivered:[],cancelled:[]})[o.status]]){const option=document.createElement('option');option.value=status;option.textContent=labels[status];select.append(option)}const button=add('button','Сохранить статус');button.className='btn secondary';button.onclick=async()=>{button.disabled=true;try{await request('status',{id:o.id,status:select.value});await load()}catch(e){message(e);button.disabled=false}};root.append(card)}if(!root.children.length)root.textContent='Заказов пока нет.'}
$('#login').onsubmit=async e=>{e.preventDefault();try{await request('login',{password:$('#password').value});$('#password').value='';$('#message').textContent='';await load()}catch(e){message(e)}};$('#refresh').onclick=load;$('#filter').onchange=render;$('#logout').onclick=async()=>{await request('logout',{});orders=[];$('#orders').replaceChildren();$('#dashboard').hidden=true;$('#login').hidden=false};$('#export').onclick=()=>{const cell=v=>'"'+String(v??'').replace(/^[=+@\-]/,"'$&").replaceAll('"','""')+'"';const rows=[['Номер','Дата','Статус','Оплата','Имя','Телефон','Город','Адрес','Сумма GEL','Товары'],...orders.map(o=>[o.id,new Date(o.createdAt*1000).toISOString(),o.status,o.paymentStatus,o.name,o.phone,o.city,o.address,o.totalCents/100,o.items.map(x=>x.name.ru+' × '+x.qty).join('; ')])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='drivebox-orders.csv';a.click();URL.revokeObjectURL(url)};load();

let inventoryLoaded=false;
$('#stock-form').onsubmit=async e=>{e.preventDefault();try{await request('inventory',{id:$('#stock-product').value,stock:Number($('#stock-count').value)});$('#message').textContent='Остаток сохранён.';}catch(e){message(e)}};
fetch('/api/catalog').then(r=>r.json()).then(items=>{for(const p of items){const o=document.createElement('option');o.value=p.id;o.textContent=p.name.ru;$('#stock-product').append(o)}});
