const CFG=window.DRIVEBOX_CONFIG, P=window.DRIVEBOX_PRODUCTS, I=window.DRIVEBOX_I18N;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function getLang(){return localStorage.getItem('drivebox_lang')||CFG.defaultLanguage||'ka'}
function syncDocumentLang(){document.documentElement.lang=getLang()}
function setLang(l){localStorage.setItem('drivebox_lang',l);location.reload()}
function t(k){return I[getLang()]?.[k]||I.ka[k]||k}
function formatGEL(v){return `${Number(v).toFixed(v%1?2:0)} ₾`}
function getCart(){try{return JSON.parse(localStorage.getItem('drivebox_cart')||'[]')}catch{return[]}}
function saveCart(c){localStorage.setItem('drivebox_cart',JSON.stringify(c));updateCartBadge()}
function addToCart(id,qty=1){let c=getCart();const row=c.find(x=>x.id===id);if(row)row.qty+=qty;else c.push({id,qty});saveCart(c);showToast(t('add'))}
function removeFromCart(id){saveCart(getCart().filter(x=>x.id!==id));renderCheckout()}
function cartCount(){return getCart().reduce((a,b)=>a+b.qty,0)}
function updateCartBadge(){$$('.cart-count').forEach(el=>el.textContent=cartCount())}
function showToast(msg){let n=document.createElement('div');n.textContent=msg;n.style.cssText='position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:#fff;color:#111;padding:11px 16px;border-radius:999px;font-weight:800;z-index:100;box-shadow:0 12px 40px #0008';document.body.appendChild(n);setTimeout(()=>n.remove(),1400)}
function productUrl(p){return `products/${p.slug}.html`}
function renderHeader(){const root=$('#site-header');if(!root)return;root.innerHTML=`${CFG.testMode?`<div class="topbar">${t('test')}</div>`:''}<header class="header"><div class="container nav"><a class="brand" href="${root.dataset.depth||''}index.html">DRIVE<span>BOX</span></a><nav class="navlinks"><a href="${root.dataset.depth||''}index.html#products">${t('shop')}</a><a href="${root.dataset.depth||''}legal/delivery.html">${t('delivery')}</a><a href="${root.dataset.depth||''}legal/returns.html">${t('returns')}</a><a href="${root.dataset.depth||''}legal/contact.html">${t('contact')}</a></nav><div class="nav-actions"><select class="lang" aria-label="Language"><option value="ka">KA</option><option value="ru">RU</option><option value="en">EN</option></select><a class="cart-btn" href="${root.dataset.depth||''}checkout.html">${t('cart')} <span class="cart-count">0</span></a></div></div></header>`;const sel=$('.lang',root);sel.value=getLang();sel.onchange=e=>setLang(e.target.value);updateCartBadge()}
function renderFooter(){const root=$('#site-footer');if(!root)return;const d=root.dataset.depth||'';root.innerHTML=`<footer class="footer"><div class="container footer-grid"><div><div class="brand">DRIVE<span>BOX</span></div><p>${t('footer')}</p></div><div><b>${t('shop')}</b><a href="${d}index.html#products">${t('shop')}</a><a href="${d}legal/delivery.html">${t('delivery')}</a><a href="${d}legal/returns.html">${t('returns')}</a></div><div><b>${t('legalSeller')}</b><a href="${d}legal/terms.html">${t('terms')}</a><a href="${d}legal/privacy.html">${t('privacy')}</a><a href="${d}legal/contact.html">${t('contact')}</a></div></div></footer>`}
function renderHome(){const root=$('#products-grid');if(!root)return;const l=getLang();root.innerHTML=P.map(p=>`<a class="product-card" href="${productUrl(p)}"><div class="product-image"><img src="${p.image}" alt="${p.imageAlt}" loading="lazy" referrerpolicy="no-referrer"></div><div class="product-body"><span class="pill">${p.supplier}</span><h3>${p.name[l]}</h3><p>${p.tagline[l]}</p><span class="price">${formatGEL(p.price)}</span><span class="compare">${formatGEL(p.compareAt)}</span></div></a>`).join('')}
function renderProduct(){const root=$('#product-root');if(!root)return;const id=document.body.dataset.product;const p=P.find(x=>x.id===id);if(!p)return;const l=getLang();document.title=`${p.name[l]} — ${CFG.brand}`;root.innerHTML=`<section class="product-hero"><div class="container product-layout"><div class="product-main-image"><img src="${p.image}" alt="${p.imageAlt}" referrerpolicy="no-referrer"></div><div class="product-info"><div class="kicker">${p.supplier}</div><h1>${p.name[l]}</h1><p class="lead">${p.tagline[l]}</p><div class="buybox"><div><span class="price">${formatGEL(p.price)}</span><span class="compare">${formatGEL(p.compareAt)}</span></div><div class="cta-row"><button class="btn primary" id="add-product">${t('add')}</button><button class="btn secondary" id="buy-product" type="button">${t('buy')}</button></div><div class="micro"><div><span class="check">✓</span>${t('productDelivery')}</div><div><span class="check">✓</span>${t('productWarranty')}</div><div><span class="check">✓</span>${t('productSupport')}</div></div></div></div></div></section><section class="section"><div class="container"><div class="section-head"><h2>${t('how')}</h2></div><div class="bullet-list">${p.bullets[l].map(x=>`<div class="bullet">✓ ${x}</div>`).join('')}</div></div></section><section class="section"><div class="container faq"><h2>${t('faq')}</h2><details><summary>${t('faq1q')}</summary><p>${t('faq1a')}</p></details><details><summary>${t('faq2q')}</summary><p>${t('faq2a')}</p></details><details><summary>${t('faq3q')}</summary><p>${t('faq3a')}</p></details></div></section>`;$('#add-product').onclick=()=>addToCart(p.id);$('#buy-product').onclick=()=>{addToCart(p.id);location.href='../checkout.html'}}
function shippingCost(subtotal,city,method){if(subtotal>=CFG.shipping.freeFrom)return 0;if((city||'').toLowerCase().includes('tbil')||(city||'').includes('თბილის')||(city||'').includes('тбил'))return method==='same'?CFG.shipping.tbilisiSameDay:CFG.shipping.tbilisiNextDay;return CFG.shipping.regions}
function renderCheckout(){const itemsRoot=$('#cart-items');if(!itemsRoot)return;const c=getCart(),l=getLang();if(!c.length){itemsRoot.innerHTML=`<p>${t('empty')}</p>`;$('#checkout-submit').disabled=true;updateTotals();return}itemsRoot.innerHTML=c.map(row=>{const p=P.find(x=>x.id===row.id);return `<div class="cart-line"><img src="${p.image}" alt="${p.imageAlt}" referrerpolicy="no-referrer"><div><b>${p.name[l]}</b><div class="muted">${row.qty} × ${formatGEL(p.price)}</div></div><div><b>${formatGEL(p.price*row.qty)}</b><br><button class="btn secondary" style="padding:5px 9px;margin-top:6px" onclick="removeFromCart('${p.id}')">×</button></div></div>`}).join('');updateTotals()}
function updateTotals(){const c=getCart();const subtotal=c.reduce((sum,row)=>{const p=P.find(x=>x.id===row.id);return sum+p.price*row.qty},0);const city=$('#city')?.value||'Tbilisi',method=$('#delivery-method')?.value||'same';const ship=c.length?shippingCost(subtotal,city,method):0;$('#subtotal-val')&&($('#subtotal-val').textContent=formatGEL(subtotal));$('#shipping-val')&&($('#shipping-val').textContent=ship?formatGEL(ship):'0 ₾');$('#total-val')&&($('#total-val').textContent=formatGEL(subtotal+ship));return {subtotal,ship,total:subtotal+ship}}
function initCheckout(){renderCheckout();['city','delivery-method'].forEach(id=>$('#'+id)?.addEventListener('input',updateTotals));const form=$('#checkout-form');if(form)form.addEventListener('submit',e=>{e.preventDefault();const totals=updateTotals();const fd=new FormData(form);const draft={name:fd.get('name'),phone:fd.get('phone'),city:fd.get('city'),address:fd.get('address'),notes:fd.get('notes'),deliveryMethod:$('#delivery-method')?.value||'same',totals,cart:getCart(),createdAt:new Date().toISOString()};localStorage.setItem('drivebox_order_draft',JSON.stringify(draft));if(CFG.testMode){$('#checkout-message').className='notice';$('#checkout-message').textContent=t('test');return}if(!CFG.paypal.clientId||CFG.paypal.clientId.includes('REPLACE')){$('#checkout-message').className='notice';$('#checkout-message').textContent='PayPal Client ID is not configured.';return}location.href='paypal.html'});}
function initLegal(){const root=$('#legal-seller');if(root)root.innerHTML=`<b>${CFG.seller.legalName}</b><br>${CFG.seller.idNumber}<br>${CFG.seller.address}<br>${CFG.seller.phone}<br>${CFG.seller.email}`}
document.addEventListener('DOMContentLoaded',()=>{syncDocumentLang();renderHeader();renderFooter();renderHome();renderProduct();initCheckout();initLegal();});
