/* Server-backed checkout; prices and payment state are authoritative on the server. */
const commerceText={
 ru:{price_changed:'Цена или доставка изменились. Обновите страницу и проверьте сумму.',paymentMethod:'Способ оплаты',cod:'Оплата при получении',paypal:'PayPal · оплата в USD',test:'Тестовый заказ — без оплаты',email:'Email для подтверждения (необязательно)',consent:'Я ознакомился с условиями заказа и политикой конфиденциальности',sending:'Сохраняем заказ…',unavailable:'Оформление временно недоступно. Попробуйте позже.',error:'Не удалось выполнить запрос. Повторите попытку.',same_day_unavailable:'Доставка сегодня доступна только в Тбилиси до 15:00. Выберите следующий день.',out_of_stock:'Недостаточно товара в наличии. Измените количество.',invalid_phone:'Проверьте номер телефона.',invalid_email:'Проверьте email.',consent_required:'Подтвердите ознакомление с условиями.',rate_limit:'Слишком много попыток. Подождите и повторите.',request_conflict:'Состав заказа изменился. Повторите оформление.',payment_service_error:'Платёжный сервис временно недоступен. Ваш заказ сохранён; попробуйте оплатить позже.',payment_unavailable:'Этот способ оплаты пока недоступен.',store_not_ready:'Магазин ещё готовится к приёму заказов.',invalid_fields:'Проверьте заполнение полей.',invalid_cart:'Проверьте товары и количество в корзине.',continueShopping:'Продолжить покупки',receipt:'Ваш заказ',saved:'Заказ сохранён. Сохраните ссылку на эту страницу, чтобы проверить статус.',pay:'Перейти к оплате',retry:'Обновить статус',new:'Принят',confirmed:'Подтверждён',shipped:'Отправлен',delivered:'Доставлен',cancelled:'Отменён',unpaid:'Не оплачен',paid:'Оплачен',review_required:'Проверка платежа',status:'Статус заказа',payment:'Оплата',testNotice:'Это тестовый заказ. Оплата и доставка не выполняются.',noReceipt:'Ссылка на заказ не найдена. Откройте сохранённую ссылку подтверждения.',fx:'К оплате через PayPal',terms:'Условия заказа',privacy:'Конфиденциальность',quantity:'Количество',loading:'Загрузка…'},
 en:{price_changed:'Price or delivery changed. Reload and review the total.',paymentMethod:'Payment method',cod:'Pay on delivery',paypal:'PayPal · charged in USD',test:'Test order — no payment',email:'Confirmation email (optional)',consent:'I have read the order terms and privacy policy',sending:'Saving your order…',unavailable:'Checkout is temporarily unavailable. Please try later.',error:'Request failed. Please retry.',same_day_unavailable:'Same-day delivery is available in Tbilisi before 15:00. Choose next day.',out_of_stock:'Insufficient stock. Adjust the quantity.',invalid_phone:'Check your phone number.',invalid_email:'Check your email.',consent_required:'Please acknowledge the terms.',rate_limit:'Too many attempts. Please wait and retry.',request_conflict:'Your order changed. Please submit again.',payment_service_error:'Payment service is unavailable. Your order is saved; try paying later.',payment_unavailable:'This payment method is unavailable.',store_not_ready:'The store is preparing to accept orders.',invalid_fields:'Please check the form fields.',invalid_cart:'Check cart items and quantities.',continueShopping:'Continue shopping',receipt:'Your order',saved:'Order saved. Keep this page link to check its status.',pay:'Continue to payment',retry:'Refresh status',new:'Received',confirmed:'Confirmed',shipped:'Shipped',delivered:'Delivered',cancelled:'Cancelled',unpaid:'Unpaid',paid:'Paid',review_required:'Payment review',status:'Order status',payment:'Payment',testNotice:'This is a test order. No payment or delivery will take place.',noReceipt:'Order link not found. Open your saved confirmation link.',fx:'PayPal charge',terms:'Order terms',privacy:'Privacy',quantity:'Quantity',loading:'Loading…'},
 ka:{price_changed:'ფასი ან მიწოდება შეიცვალა. განაახლეთ გვერდი და შეამოწმეთ ჯამი.',paymentMethod:'გადახდის მეთოდი',cod:'გადახდა მიღებისას',paypal:'PayPal · გადახდა USD-ში',test:'სატესტო შეკვეთა — გადახდის გარეშე',email:'დადასტურების ელფოსტა (არასავალდებულო)',consent:'გავეცანი შეკვეთის პირობებსა და კონფიდენციალურობის პოლიტიკას',sending:'შეკვეთა ინახება…',unavailable:'შეკვეთის გაფორმება დროებით მიუწვდომელია. სცადეთ მოგვიანებით.',error:'მოთხოვნა ვერ შესრულდა. სცადეთ ხელახლა.',same_day_unavailable:'იმავე დღეს მიწოდება ხელმისაწვდომია თბილისში 15:00-მდე. აირჩიეთ შემდეგი დღე.',out_of_stock:'მარაგი არასაკმარისია. შეცვალეთ რაოდენობა.',invalid_phone:'შეამოწმეთ ტელეფონის ნომერი.',invalid_email:'შეამოწმეთ ელფოსტა.',consent_required:'დაადასტურეთ პირობების გაცნობა.',rate_limit:'ძალიან ბევრი მცდელობა. სცადეთ მოგვიანებით.',request_conflict:'შეკვეთა შეიცვალა. სცადეთ ხელახლა.',payment_service_error:'გადახდის სერვისი მიუწვდომელია. შეკვეთა შენახულია; სცადეთ მოგვიანებით.',payment_unavailable:'გადახდის ეს მეთოდი მიუწვდომელია.',store_not_ready:'მაღაზია ემზადება შეკვეთების მისაღებად.',invalid_fields:'შეამოწმეთ ველები.',invalid_cart:'შეამოწმეთ კალათა და რაოდენობა.',continueShopping:'შოპინგის გაგრძელება',receipt:'თქვენი შეკვეთა',saved:'შეკვეთა შენახულია. შეინახეთ გვერდის ბმული სტატუსის სანახავად.',pay:'გადახდაზე გადასვლა',retry:'სტატუსის განახლება',new:'მიღებულია',confirmed:'დადასტურებულია',shipped:'გაგზავნილია',delivered:'მიწოდებულია',cancelled:'გაუქმებულია',unpaid:'გადაუხდელია',paid:'გადახდილია',review_required:'გადახდის შემოწმება',status:'შეკვეთის სტატუსი',payment:'გადახდა',testNotice:'ეს სატესტო შეკვეთაა. გადახდა და მიწოდება არ შესრულდება.',noReceipt:'შეკვეთის ბმული ვერ მოიძებნა. გახსენით შენახული დადასტურების ბმული.',fx:'PayPal-ით გადასახდელი',terms:'შეკვეთის პირობები',privacy:'კონფიდენციალურობა',quantity:'რაოდენობა',loading:'იტვირთება…'}
};
for(const [lang,copy] of Object.entries({
 ru:{invalid_name:'Укажите имя: от 2 до 120 символов.',invalid_city:'Укажите город: от 2 до 100 символов.',invalid_address:'Укажите полный адрес: улицу и номер дома (от 5 до 300 символов).',invalid_notes:'Комментарий должен быть не длиннее 1000 символов.'},
 en:{invalid_name:'Enter a name of 2–120 characters.',invalid_city:'Enter a city of 2–100 characters.',invalid_address:'Enter the full street address and house number (5–300 characters).',invalid_notes:'Notes must not exceed 1000 characters.'},
 ka:{invalid_name:'მიუთითეთ სახელი: 2–120 სიმბოლო.',invalid_city:'მიუთითეთ ქალაქი: 2–100 სიმბოლო.',invalid_address:'მიუთითეთ სრული მისამართი, ქუჩა და სახლის ნომერი (5–300 სიმბოლო).',invalid_notes:'კომენტარი არ უნდა აღემატებოდეს 1000 სიმბოლოს.'}
}))Object.assign(commerceText[lang],copy);
function validateCustomer(form){
 const rules={name:[2,120],city:[2,100],address:[5,300],phone:[7,30],email:[0,200],notes:[0,1000]};
 for(const [id,[min,max]] of Object.entries(rules)){
  const field=form.querySelector('#'+id),value=field.value.trim();
  let invalid=value.length<min||value.length>max;
  if(id==='phone')invalid=invalid||!/^\+?[\d ()-]{7,30}$/.test(value)||value.replace(/\D/g,'').length<7||value.replace(/\D/g,'').length>15;
  if(id==='email'&&value)invalid=invalid||!field.validity.valid;
  field.setCustomValidity(invalid?ct('invalid_'+id):'');
  field.setAttribute('aria-invalid',String(invalid));
  if(invalid){field.reportValidity();field.focus();return false}
 }
 return true;
}
function ct(k){return commerceText[getLang()]?.[k]||commerceText.en[k]||commerceText[getLang()].error}
async function api(path,body,extra={}){let r;try{r=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...extra},body:body?JSON.stringify(body):undefined});}catch{throw new Error('unavailable')}let data;try{data=await r.json()}catch{throw new Error('unavailable')}if(!r.ok)throw new Error(data.error||'error');return data}
for(const [lang,copy] of Object.entries({ru:{receiptTitle:'Заказ',paymentNote:'Тестовый заказ сохраняется на сервере. Оплата и доставка не выполняются.'},en:{receiptTitle:'Order',paymentNote:'Test orders are saved on the server. No payment or delivery takes place.'},ka:{receiptTitle:'შეკვეთა',paymentNote:'სატესტო შეკვეთა ინახება სერვერზე. გადახდა და მიწოდება არ შესრულდება.'}}))Object.assign(I[lang],copy);
let storeSettings=null,checkoutBusy=false;
const baseRenderCheckout=renderCheckout;
renderCheckout=function(){baseRenderCheckout();const btn=$('#checkout-submit');if(btn)btn.disabled=checkoutBusy||!getCart().length||!storeSettings?.acceptingOrders;const rows=$$('.cart-line');rows.forEach((el,i)=>{const row=getCart()[i];const controls=document.createElement('div');controls.className='quantity-controls';for(const [label,delta] of [['−',-1],['+',1]]){const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('aria-label',ct('quantity')+' '+label);b.disabled=checkoutBusy||(delta>0&&row.qty>=20);b.onclick=()=>{const c=getCart();const item=c.find(x=>x.id===row.id);item.qty+=delta;saveCart(c.filter(x=>x.qty>0));renderCheckout()};controls.append(b)}el.children[1].append(controls)});};
function getPaymentMethod(){return $('#payment-method input:checked')?.value||''}
function updateCommerceLabels(){
 for(const el of $$('[data-t="sellerPending"]'))el.hidden=!!storeSettings?.seller?.name;
 for(const el of $$('[data-ct]'))el.textContent=ct(el.dataset.ct);
 const methods=$('#payment-method');
 if(methods&&storeSettings){const old=getPaymentMethod();methods.replaceChildren();const legend=document.createElement('legend');legend.textContent=ct('paymentMethod');methods.append(legend);
  for(const method of storeSettings.paymentMethods){const label=document.createElement('label');label.className='payment-option';const input=document.createElement('input');input.type='radio';input.name='paymentMethod';input.value=method;input.required=true;input.checked=method===old;input.disabled=['card','paypal'].includes(method)&&!storeSettings.paypal?.configured;
   const text=document.createElement('span');text.textContent=ct(method);if(method==='card'){const small=document.createElement('small');small.textContent='Visa / Mastercard';text.append(small)}label.append(input,text);methods.append(label)}
  if(!getPaymentMethod()){const first=methods.querySelector('input:not(:disabled)');if(first)first.checked=true}
 }
 const note=$('#payment-note');if(note)note.textContent=storeSettings?(storeSettings.testMode?ct('sandboxNotice'):''):ct('unavailable');
}
async function loadStore(){try{const [settings,catalog]=await Promise.all([api('/api/config'),api('/api/catalog')]);storeSettings=settings;CFG.testMode=settings.testMode;CFG.promotion={enabled:settings.discountPercent>0,discountPercent:settings.discountPercent,freeShipping:settings.freeShipping};for(const p of P){const s=catalog.find(x=>x.id===p.id);if(s){p.price=s.priceCents/100;p.stock=s.stock;}}Object.assign(CFG.seller,{legalName:settings.seller.name,idNumber:settings.seller.id,...settings.seller});renderLanguage();updateCommerceLabels();}catch{updateCommerceLabels();renderCheckout();}}
initCheckout=async function(){
 const form=$('#checkout-form');
 if(form){
  const email=document.createElement('div');email.className='field';email.innerHTML='<label for="email" data-ct="email"></label><input type="email" id="email" name="email" autocomplete="email" maxlength="200">';form.insertBefore(email,$('#phone').closest('.field').nextSibling);
  const fields=document.createElement('div');fields.innerHTML='<fieldset id="payment-method" class="payment-methods"></fieldset><label class="consent"><input type="checkbox" id="order-consent" required><span data-ct="consent"></span></label><p class="checkout-legal"><a href="legal/terms.html" target="_blank" data-ct="terms"></a> · <a href="legal/privacy.html" target="_blank" data-ct="privacy"></a></p>';form.insertBefore(fields,$('#payment-note'));
  $('#delivery-method').value='next';$('#name').maxLength=120;$('#phone').maxLength=30;$('#city').maxLength=100;$('#address').maxLength=300;$('#notes').maxLength=1000;
  for(const field of form.querySelectorAll('input,textarea'))field.addEventListener('input',()=>{field.setCustomValidity('');field.removeAttribute('aria-invalid')});
  for(const id of ['city','delivery-method'])$('#'+id).addEventListener('input',updateTotals);
  form.addEventListener('submit',async e=>{e.preventDefault();if(checkoutBusy||!storeSettings?.acceptingOrders)return;if(!validateCustomer(form))return;checkoutBusy=true;renderCheckout();const msg=$('#checkout-message');msg.removeAttribute('data-t');msg.className='notice';msg.textContent=ct('sending');
   const payload={...Object.fromEntries(new FormData(form)),cart:getCart(),deliveryMethod:$('#delivery-method').value,consent:$('#order-consent').checked,language:getLang(),expectedTotalCents:Math.round(updateTotals().total*100)};
   const serialized=JSON.stringify(payload);let pending;try{pending=JSON.parse(sessionStorage.getItem('drivebox_pending')||'null')}catch{}
   if(!pending||pending.payload!==serialized){pending={payload:serialized,key:crypto.randomUUID()};sessionStorage.setItem('drivebox_pending',JSON.stringify(pending));}
   try{const order=await api('/api/orders',payload,{'Idempotency-Key':pending.key});sessionStorage.setItem('drivebox_receipt',JSON.stringify({id:order.id,token:order.token}));localStorage.removeItem('drivebox_order_draft');if(order.paymentMethod==='cash_on_delivery'){clearOrderedCart(order);sessionStorage.removeItem('drivebox_pending');}location.href='order.html#'+order.id+'/'+order.token;}catch(err){msg.textContent=ct(err.message);const field=form.querySelector('#'+err.message.replace('invalid_',''));if(err.message.startsWith('invalid_')&&field){field.setCustomValidity(ct(err.message));field.reportValidity();field.focus();}if(err.message==='request_conflict')sessionStorage.removeItem('drivebox_pending');}finally{checkoutBusy=false;renderCheckout();}
  });
 }
 await loadStore();if($('#receipt'))await renderReceipt();
};
document.addEventListener('drivebox:language',()=>{updateCommerceLabels();if($('#receipt')&&storeSettings)renderReceipt()});
function receiptCredentials(){if(location.hash){const [id,token]=location.hash.slice(1).split('/');if(id&&token){const v={id,token};sessionStorage.setItem('drivebox_receipt',JSON.stringify(v));return v}}try{return JSON.parse(sessionStorage.getItem('drivebox_receipt'))}catch{return null}}
let receiptBusy=false;
async function renderReceipt(){if(receiptBusy)return;receiptBusy=true;const root=$('#receipt');try{const credentials=receiptCredentials();if(!credentials){root.textContent=ct('noReceipt');return;}let order=await api('/api/order',credentials);if(order.paymentStatus==='paid')clearOrderedCart(order);
 root.replaceChildren();const add=(tag,text,cls)=>{const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;root.append(el);return el};add('h1',ct(order.paymentStatus==='paid'?'thankYou':'receipt')+' '+order.id);add('p',ct(order.paymentStatus==='paid'?'paymentSuccess':'saved'));if(order.testMode)add('p',ct('sandboxNotice'),'notice');add('p',ct('status')+': '+ct(order.status));add('p',ct('payment')+': '+ct(order.paymentStatus));for(const item of order.items)add('p',item.name[getLang()]+' × '+item.qty+' — '+formatGEL(item.unitCents*item.qty/100));add('h2',t('total')+': '+formatGEL(order.totalCents/100));add('p',order.city+', '+order.address);if(order.usd)add('p',ct('fx')+': '+order.usd+' USD');
 if(['card','paypal'].includes(order.paymentMethod)&&['pending','unpaid','failed','cancelled'].includes(order.paymentStatus)&&order.status!=='cancelled'){
  const box=add('div','','payment-box');await mountPayment(box,order,credentials,async confirmed=>{if(confirmed.paymentStatus==='paid'||confirmed.paymentMethod==='cash_on_delivery'){clearOrderedCart(confirmed);receiptBusy=false;await renderReceipt();}else{const message=document.createElement('p');message.className='notice';message.textContent=ct('paymentPending');box.prepend(message)}});
 }
 const refresh=add('button',ct('retry'),'btn secondary');refresh.onclick=()=>renderReceipt();const link=add('a',ct('continueShopping'),'btn secondary');link.href='index.html#products';
 }catch(err){root.textContent=ct(err.message);const retry=document.createElement('button');retry.className='btn secondary';retry.textContent=ct('retry');retry.onclick=()=>renderReceipt();root.append(retry);}finally{receiptBusy=false}}

function clearOrderedCart(order){const key='drivebox_cart_cleared_'+order.id;if(localStorage.getItem(key))return;const cart=getCart();for(const item of order.items){const row=cart.find(x=>x.id===item.id);if(row)row.qty=Math.max(0,row.qty-item.qty)}saveCart(cart.filter(x=>x.qty>0));localStorage.setItem(key,'1');sessionStorage.removeItem('drivebox_pending');}
