CREATE TABLE IF NOT EXISTS orders (
 id TEXT PRIMARY KEY, token TEXT NOT NULL, idem TEXT UNIQUE NOT NULL,
 fingerprint TEXT NOT NULL, created DOUBLE PRECISION NOT NULL,
 status TEXT NOT NULL, payment TEXT NOT NULL, payment_status TEXT NOT NULL,
 paypal_id TEXT UNIQUE, capture_id TEXT UNIQUE, usd TEXT, body JSONB NOT NULL,
 paypal_env TEXT, paypal_account TEXT, payer_id TEXT, payer_email TEXT,
 payment_phase TEXT NOT NULL DEFAULT 'not_started', paypal_started DOUBLE PRECISION
);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, expires DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY, created DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id BIGSERIAL PRIMARY KEY, order_id TEXT, created DOUBLE PRECISION, action TEXT);
CREATE TABLE IF NOT EXISTS outbox(id BIGSERIAL PRIMARY KEY, order_id TEXT, subject TEXT, recipient TEXT, body TEXT, attempts INTEGER NOT NULL DEFAULT 0, next_try DOUBLE PRECISION NOT NULL DEFAULT 0, sent DOUBLE PRECISION);
CREATE TABLE IF NOT EXISTS inventory(id TEXT PRIMARY KEY, stock INTEGER NOT NULL CHECK(stock>=0));
CREATE TABLE IF NOT EXISTS refunds(id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), cents INTEGER NOT NULL CHECK(cents>0));
CREATE INDEX IF NOT EXISTS orders_created ON orders(created DESC);
CREATE INDEX IF NOT EXISTS refunds_order ON refunds(order_id);
CREATE TABLE IF NOT EXISTS request_limits(id TEXT PRIMARY KEY, hits INTEGER NOT NULL, expires DOUBLE PRECISION NOT NULL);
